
-- 1
CREATE DATABASE ConstructionProjects;

-- 2
USE ConstructionProjects;
CREATE TABLE JOB (
	JOB_CODE 			CHAR(3) 		NOT NULL UNIQUE,
	JOB_DESCRIPTION 	VARCHAR(35) 	NOT NULL,
	JOB_CHG_HOUR	 	NUMERIC(6,2) 	NOT NULL,
	JOB_LAST_UPDATE	DATETIME	NOT NULL,
PRIMARY KEY (JOB_CODE));

-- 3
INSERT INTO JOB VALUES('500','Reference Librarian',50.75,'2013-07-15');
INSERT INTO JOB VALUES('501','Database analyst',65.25,'2013-01-18');

-- 4
UPDATE JOB
SET JOB_CHG_HOUR = 70.00
WHERE JOB_CODE = '501';

-- 5
DELETE FROM JOB 
WHERE JOB_CHG_HOUR > 60.00;

-- 6
USE sales;
SELECT 	COUNT(INV_NUMBER) AS TOTAL_INVOICES
FROM 	invoice;

-- 7
SELECT *
FROM customer
WHERE CUS_BALANCE > 500;

-- 8
SELECT *
FROM vendor
WHERE V_CONTACT LIKE 'Sm%';

-- 9
SELECT SUM(LINE_UNITS) AS SOLDITEMS
FROM line
WHERE P_CODE = 'PVC23DRT';

-- 10
SELECT		INV_NUMBER,
SUM(LINE_UNITS * LINE_PRICE) AS 'TOTAL_PER_INVOICE'
FROM		LINE
GROUP BY	INV_NUMBER;



